server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # user server (without auth)
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user-server/actuator/**, /user-server/signup/**
          filters:
            - RewritePath=/user-server/(?<segment>.*), /$\{segment}
        # user server
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user-server/users/**
          filters:
            - RewritePath=/user-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # user-cache server (without auth)
        - id: user-cache
          uri: lb://USER-CACHE
          predicates:
            - Path=/user-cache/actuator/**, /user-cache/private/**
          filters:
            - RewritePath=/user-cache/(?<segment>.*), /$\{segment}
        # auth server (without auth)
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth-server/actuator/**, /auth-server/login/**, /auth-server/refresh/**, /auth-server/oauth/**
          filters:
            - RewritePath=/auth-server/(?<segment>.*), /$\{segment}
        # auth server
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth-server/logout/**
          filters:
            - RewritePath=/auth-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # relation server
        - id: relation-server
          uri: lb://RELATION-SERVER
          predicates:
            - Path=/relation-server/users/**
          filters:
            - RewritePath=/relation-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # post server (without auth)
        - id: post-server
          uri: lb://POST-SERVER
          predicates:
            - Path=/post-server/actuator/**
          filters:
            - RewritePath=/post-server/(?<segment>.*), /$\{segment}
        # post-cache server (without auth)
        - id: post-cache
          uri: lb://POST-CACHE
          predicates:
            - Path=/post-cache/private/**
          filters:
            - RewritePath=/post-cache/(?<segment>.*), /$\{segment}
        # post server
        - id: post-server
          uri: lb://POST-SERVER
          predicates:
            - Path=/post-server/posts/**
          filters:
            - RewritePath=/post-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # comment server
        - id: comment-server
          uri: lb://COMMENT-SERVER
          predicates:
            - Path=/comment-server/posts/**
          filters:
            - RewritePath=/comment-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # feed server
        - id: feed-server
          uri: lb://FEED-SERVER
          predicates:
            - Path=/feed-server/feed/**
          filters:
            - RewritePath=/feed-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter
        # notification server
        - id: notification-server
          uri: lb://NOTIFICATION-SERVER
          predicates:
            - Path=/notification-server/notifications/**
          filters:
            - RewritePath=/notification-server/(?<segment>.*), /$\{segment}
            - JwtAuthorizationFilter